query FindRoom($where: RoomWhereUniqueInput!) {
  findRoom(where: $where) {
    attenders {
      finishedAt
      gameState
      handCards {
        color
        number
        type
        id
      }
      iconBackgroundColor
      iconEmoji
      id
      isMyTurn
      joinedAt
      name
      role
    }
    deckCards {
      color
      number
      type
      id
    }
    fieldCards {
      color
      number
      type
      id
    }
    gameState
    id
  }
}
