version: "3.8"

services:
  app:
    container_name: usa-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - type: bind
        source: ../
        target: /workspaces/usa/
      - type: volume
        source: pnpm-store
        target: /workspaces/usa/.pnpm-store/
    tty: true

volumes:
  pnpm-store:
    driver: local
